In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('Telco-Customer-Churn.csv')

In [3]:
dataset

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85   
1                  No               Mailed check          56.95        1889.5   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
4                 Yes           Electronic check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              Yes               Mailed check          84.80        1990.5   
7039              Yes    Credit card (automatic)         103.20        7362.9   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40         306.6   
7042              Yes  Bank transfer (automatic)         105.65        6844.5   

     Churn  
0       No  
1       No  
2      Yes  
3       No  
4      Yes  
...    ...  
7038    No  
7039    No  
7040    No  
7041   Yes  
7042    No  

[7043 rows x 21 columns]

In [4]:
dataset.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [5]:
dataset.tail()

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
7038              Yes               Mailed check          84.80        1990.5   
7039              Yes    Credit card (automatic)         103.20        7362.9   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40         306.6   
7042              Yes  Bank transfer (automatic)         105.65        6844.5   

     Churn  
7038    No  
7039    No  
7040    No  
7041   Yes  
7042    No  

[5 rows x 21 columns]

In [6]:
dataset.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [7]:
y=dataset['Churn']

In [8]:
y

0        No
1        No
2       Yes
3        No
4       Yes
       ... 
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7043, dtype: object

In [9]:
dataset.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
le=LabelEncoder()

In [12]:
y=le.fit_transform(y.values.ravel())

In [13]:
y=pd.DataFrame(y)

In [14]:
y

0
0     0
1     0
2     1
3     0
4     1
...  ..
7038  0
7039  0
7040  0
7041  1
7042  0

[7043 rows x 1 columns]

In [15]:
dataset=dataset.drop(['customerID','Churn'],axis=1)

In [16]:
dataset

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No   
1       Male              0      No         No      34          Yes   
2       Male              0      No         No       2          Yes   
3       Male              0      No         No      45           No   
4     Female              0      No         No       2          Yes   
...      ...            ...     ...        ...     ...          ...   
7038    Male              0     Yes        Yes      24          Yes   
7039  Female              0     Yes        Yes      72          Yes   
7040  Female              0     Yes        Yes      11           No   
7041    Male              1     Yes         No       4          Yes   
7042    Male              0      No         No      66          Yes   

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes   
1                   No             DSL            Yes           No   
2                   No             DSL            Yes          Yes   
3     No phone service             DSL            Yes           No   
4                   No     Fiber optic             No           No   
...                ...             ...            ...          ...   
7038               Yes             DSL            Yes           No   
7039               Yes     Fiber optic             No          Yes   
7040  No phone service             DSL            Yes           No   
7041               Yes     Fiber optic             No           No   
7042                No     Fiber optic            Yes           No   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  
0                 Yes           Electronic check           29.85        29.85  
1                  No               Mailed check           56.95       1889.5  
2                 Yes               Mailed check           53.85       108.15  
3                  No  Bank transfer (automatic)           42.30      1840.75  
4                 Yes           Electronic check           70.70       151.65  
...               ...                        ...             ...          ...  
7038              Yes               Mailed check           84.80       1990.5  
7039              Yes    Credit card (automatic)          103.20       7362.9  
7040              Yes           Electronic check           29.60       346.45  
7041              Yes               Mailed check           74.40        306.6  
7042              Yes  Bank transfer (automatic)          105.65       6844.5  

[7043 rows x 19 columns]

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
from sklearn.pipeline import Pipeline

In [20]:
from sklearn.compose import ColumnTransformer

In [21]:
preprocess=ColumnTransformer([('sc',StandardScaler(),['tenure','MonthlyCharges','TotalCharges']),('encoder',OneHotEncoder(sparse_output=False),['gender','Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','Contract','PaperlessBilling','PaymentMethod'])])

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
pipeline_logistic=Pipeline([('model_logis',LogisticRegression(random_state=42,solver='liblinear',C=0.01,penalty='l2'))])

In [24]:
x=dataset

In [25]:
x

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No   
1       Male              0      No         No      34          Yes   
2       Male              0      No         No       2          Yes   
3       Male              0      No         No      45           No   
4     Female              0      No         No       2          Yes   
...      ...            ...     ...        ...     ...          ...   
7038    Male              0     Yes        Yes      24          Yes   
7039  Female              0     Yes        Yes      72          Yes   
7040  Female              0     Yes        Yes      11           No   
7041    Male              1     Yes         No       4          Yes   
7042    Male              0      No         No      66          Yes   

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes   
1                   No             DSL            Yes           No   
2                   No             DSL            Yes          Yes   
3     No phone service             DSL            Yes           No   
4                   No     Fiber optic             No           No   
...                ...             ...            ...          ...   
7038               Yes             DSL            Yes           No   
7039               Yes     Fiber optic             No          Yes   
7040  No phone service             DSL            Yes           No   
7041               Yes     Fiber optic             No           No   
7042                No     Fiber optic            Yes           No   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  
0                 Yes           Electronic check           29.85        29.85  
1                  No               Mailed check           56.95       1889.5  
2                 Yes               Mailed check           53.85       108.15  
3                  No  Bank transfer (automatic)           42.30      1840.75  
4                 Yes           Electronic check           70.70       151.65  
...               ...                        ...             ...          ...  
7038              Yes               Mailed check           84.80       1990.5  
7039              Yes    Credit card (automatic)          103.20       7362.9  
7040              Yes           Electronic check           29.60       346.45  
7041              Yes               Mailed check           74.40        306.6  
7042              Yes  Bank transfer (automatic)          105.65       6844.5  

[7043 rows x 19 columns]

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [28]:
x_train['TotalCharges'] = x_train['TotalCharges'].replace(' ', np.nan)
nan_indices_train = x_train[x_train['TotalCharges'].isna()].index
x_train.dropna(inplace=True)
y_train = y_train.drop(nan_indices_train)
x_train=preprocess.fit_transform(x_train)

In [29]:
pipeline_logistic.fit(x_train,y_train.values.ravel())

Pipeline(steps=[('model_logis',
                 LogisticRegression(C=0.01, random_state=42,
                                    solver='liblinear'))])

In [30]:
x_test['TotalCharges'] = x_test['TotalCharges'].replace(' ', np.nan)
nan_indices_test = x_test[x_test['TotalCharges'].isna()].index
x_test.dropna(inplace=True)
y_test = y_test.drop(nan_indices_test)
x_test=preprocess.fit_transform(x_test)

In [31]:
y_pred_logistic=pipeline_logistic.predict(x_test)

In [32]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [33]:
acc_logistic=accuracy_score(y_test,y_pred_logistic)

In [34]:
acc_logistic

0.8217329545454546

In [35]:
print(confusion_matrix(y_test,y_pred_logistic))

[[946  89]
 [162 211]]


In [36]:
print(classification_report(y_test,y_pred_logistic))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88      1035
           1       0.70      0.57      0.63       373

    accuracy                           0.82      1408
   macro avg       0.78      0.74      0.75      1408
weighted avg       0.81      0.82      0.82      1408



In [37]:
from sklearn.ensemble import RandomForestClassifier

In [38]:
pipeline_rf=Pipeline([('model_rf',RandomForestClassifier(bootstrap=True,max_features='sqrt',random_state=42,n_estimators=100,min_samples_split=10,min_samples_leaf=7,max_depth=30))])

In [39]:
pipeline_rf.fit(x_train,y_train.values.ravel())

Pipeline(steps=[('model_rf',
                 RandomForestClassifier(max_depth=30, min_samples_leaf=7,
                                        min_samples_split=10,
                                        random_state=42))])

In [40]:
y_pred_rf=pipeline_rf.predict(x_test)

In [41]:
acc_rf=accuracy_score(y_test,y_pred_rf)

In [42]:
acc_rf

0.8103693181818182

In [43]:
print(confusion_matrix(y_test,y_pred_rf))

[[957  78]
 [189 184]]


In [44]:
print(classification_report(y_test,y_pred_rf))

              precision    recall  f1-score   support

           0       0.84      0.92      0.88      1035
           1       0.70      0.49      0.58       373

    accuracy                           0.81      1408
   macro avg       0.77      0.71      0.73      1408
weighted avg       0.80      0.81      0.80      1408



In [45]:
from sklearn.tree import DecisionTreeClassifier

In [46]:
pipeline_dt=Pipeline([('model_dt',DecisionTreeClassifier(criterion='gini',max_depth=5,min_samples_split=30,min_samples_leaf=10,max_features=None))])

In [47]:
pipeline_dt.fit(x_train,y_train.values.ravel())

Pipeline(steps=[('model_dt',
                 DecisionTreeClassifier(max_depth=5, min_samples_leaf=10,
                                        min_samples_split=30))])

In [48]:
y_pred_dt=pipeline_dt.predict(x_test)

In [49]:
acc_dt=accuracy_score(y_test,y_pred_dt)

In [50]:
acc_dt

0.8025568181818182

In [51]:
print(confusion_matrix(y_test,y_pred_dt))

[[896 139]
 [139 234]]


In [52]:
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           0       0.87      0.87      0.87      1035
           1       0.63      0.63      0.63       373

    accuracy                           0.80      1408
   macro avg       0.75      0.75      0.75      1408
weighted avg       0.80      0.80      0.80      1408



In [53]:
from sklearn.neighbors import KNeighborsClassifier

In [54]:
pipeline=Pipeline([('model_knn',KNeighborsClassifier(n_neighbors=30,weights='uniform',metric='minkowski',p=2))])

In [55]:
pipeline.fit(x_train,y_train.values.ravel())

Pipeline(steps=[('model_knn', KNeighborsClassifier(n_neighbors=30))])

In [56]:
y_pred_knn=pipeline.predict(x_test)

In [57]:
acc_knn=accuracy_score(y_test,y_pred_knn)

In [58]:
acc_knn

0.8146306818181818

In [59]:
print(confusion_matrix(y_test,y_pred_knn))

[[930 105]
 [156 217]]


In [60]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.86      0.90      0.88      1035
           1       0.67      0.58      0.62       373

    accuracy                           0.81      1408
   macro avg       0.77      0.74      0.75      1408
weighted avg       0.81      0.81      0.81      1408



In [61]:
from sklearn.svm  import SVC

In [62]:
pipeline_svm=Pipeline([('model_svm',SVC(kernel='linear',C=0.01,verbose=False))])

In [63]:
pipeline_svm.fit(x_train,y_train.values.ravel())

Pipeline(steps=[('model_svm', SVC(C=0.01, kernel='linear'))])

In [64]:
y_pred_svm=pipeline_svm.predict(x_test)

In [65]:
acc_svm=accuracy_score(y_test,y_pred_svm)

In [66]:
acc_svm

0.8188920454545454

In [67]:
print(confusion_matrix(y_test,y_pred_svm))

[[937  98]
 [157 216]]


In [68]:
print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.86      0.91      0.88      1035
           1       0.69      0.58      0.63       373

    accuracy                           0.82      1408
   macro avg       0.77      0.74      0.75      1408
weighted avg       0.81      0.82      0.81      1408



In [69]:
!pip install xgboost

In [70]:
from xgboost import XGBClassifier

In [71]:
pipeline_xgb=Pipeline([('model_xgb',XGBClassifier(n_estimators=50,max_depth=3,learning_rate=0.1,subsample=0.5,colsample_bytree=0.7,gamma=0))])

In [72]:
pipeline_xgb.fit(x_train,y_train.values.ravel())

Pipeline(steps=[('model_xgb',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=0.7, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, feature_weights=None,
                               gamma=0, grow_policy=None, importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=3, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=50, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [73]:
y_pred_xgb=pipeline_xgb.predict(x_test)

In [74]:
acc_xgb=accuracy_score(y_test,y_pred_xgb)

In [75]:
acc_xgb

0.8167613636363636

In [76]:
print(confusion_matrix(y_test,y_pred_xgb))

[[946  89]
 [169 204]]


In [77]:
print(classification_report(y_test,y_pred_xgb))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88      1035
           1       0.70      0.55      0.61       373

    accuracy                           0.82      1408
   macro avg       0.77      0.73      0.75      1408
weighted avg       0.81      0.82      0.81      1408



In [78]:
from sklearn.naive_bayes import GaussianNB

In [79]:
pipeline_gnb=Pipeline([('model_gnb',GaussianNB(var_smoothing=1e-15))])

In [80]:
pipeline_gnb.fit(x_train,y_train.values.ravel())

Pipeline(steps=[('model_gnb', GaussianNB(var_smoothing=1e-15))])

In [81]:
y_pred_gnb=pipeline_gnb.predict(x_test)

In [82]:
acc_gnb=accuracy_score(y_test,y_pred_gnb)

In [83]:
acc_gnb

0.6960227272727273

In [84]:
print(confusion_matrix(y_test,y_pred_gnb))

[[658 377]
 [ 51 322]]


In [85]:
print(classification_report(y_test,y_pred_gnb))

              precision    recall  f1-score   support

           0       0.93      0.64      0.75      1035
           1       0.46      0.86      0.60       373

    accuracy                           0.70      1408
   macro avg       0.69      0.75      0.68      1408
weighted avg       0.80      0.70      0.71      1408



In [86]:
from sklearn.naive_bayes import BernoulliNB

In [87]:
pipeline_bnb=Pipeline([('model_bnb',BernoulliNB(fit_prior=True,alpha=5,binarize=0.0))])

In [88]:
pipeline_bnb.fit(x_train,y_train.values.ravel())

Pipeline(steps=[('model_bnb', BernoulliNB(alpha=5))])

In [89]:
y_pred_bnb=pipeline_bnb.predict(x_test)

In [90]:
acc_bnb=accuracy_score(y_test,y_pred_bnb)

In [91]:
acc_bnb

0.7322443181818182

In [92]:
print(confusion_matrix(y_test,y_pred_bnb))

[[721 314]
 [ 63 310]]


In [93]:
print(classification_report(y_test,y_pred_bnb))

              precision    recall  f1-score   support

           0       0.92      0.70      0.79      1035
           1       0.50      0.83      0.62       373

    accuracy                           0.73      1408
   macro avg       0.71      0.76      0.71      1408
weighted avg       0.81      0.73      0.75      1408



In [94]:
accuracies={'logistic_regression':acc_logistic,'random_forest_classifier':acc_rf,'decision_tree_classifier':acc_dt,'knn':acc_knn,'svm':acc_svm,'xgb':acc_xgb,'gaussian naive bayes':acc_gnb,'bernoulli naive bayes':acc_bnb}

In [95]:
descending_accuracies=sorted(accuracies.items(),key = lambda item: item[1],reverse=True)

In [96]:
df_accuracies=pd.DataFrame(descending_accuracies,columns=['models','accuracy'])

In [97]:
df_accuracies

models  accuracy
0       logistic_regression  0.821733
1                       svm  0.818892
2                       xgb  0.816761
3                       knn  0.814631
4  random_forest_classifier  0.810369
5  decision_tree_classifier  0.802557
6     bernoulli naive bayes  0.732244
7      gaussian naive bayes  0.696023

In [100]:
best_model=df_accuracies.iloc[0,0]

In [101]:
best_model

'logistic_regression'

In [102]:
import joblib

In [103]:
joblib.dump(pipeline_logistic,'logistic_regression_model.pkl')

['logistic_regression_model.pkl']

In [104]:
print("Model saved successfully")

Model saved successfully


In [108]:
#load_model=joblib.load('logistic_regression_model.pkl')

In [109]:
#y_pred=load_model.predict(x_test)

In [110]:
#y_pred[:5]